services:
  database:
    build: ./database/
    container_name: "database"
    ports:
      - "5432:5432"


  backend:
    build: ./bugboard26/
    container_name: "backend"
    tty: true
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    links:
      - "database:database"
