services:
  database:
    build: ./database/
    container_name: "database"
    ports:
      - 5432:5432
    volumes:
    - ./database/data/:/var/lib/postgresql/data

  bugboard26:
    image: bugboard26
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080